#output: TestException
#output: test

import testsupport.TestException;

function _break() as void throws TestException {
	throw new TestException("test");
}

try {
	_break();
} catch ex {
	println(typeof(ex));
	println(ex.message);
}
